Expose the skipPointerEventsCheck check
Workiva/react_testing_library pull request #48
Opened 2022-04-14 17:58 UTC by joebingham-wk

## Motivation
  

Since we've last generated our js src and wrapped the APIs, the parameter `skipPointerEventsCheck` has been exposed on UserEvent clicking APIs. These isn't a super rare use case, so this PR exposes the parameter.

## Changes
  
- Consume the last minor version of testing-library v13 (v14 was just released two weeks ago)
- Add the skipPointerEventsCheck option to `click` and `dblClick`
- Add tests

#### Release Notes
  

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Steps from PR author:
        
      - [ ] CI passes and tests correctly exercise the parameter
    - [ ] Anything falling under manual testing criteria [outlined in CONTRIBUTING.md][contributing-manual-testing]

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Client Platform member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/react_testing_library/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/react_testing_library/blob/master/CONTRIBUTING.md#manual-testing-criteria

2022-04-14 18:01 UTC, aviary2-wf commented
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

2022-04-14 18:27 UTC, joebingham-wk commented
The dev build is failing because pub is deprecated and is getting removed

2022-04-14 20:43 UTC, sydneyjodon-wk requested changes
This option will be really nice!

2022-04-14 20:43 UTC, sydneyjodon-wk commented on lib/src/user_event/user_event.dart
> +  /// ### [skipPointerEventsCheck]
It looks like this option is also available on `hover`, `unhover`, `selectOptions`, and `deselectOptions` - do we want to add it to those methods in this PR as well?

2022-04-14 20:43 UTC, sydneyjodon-wk commented on test/unit/user_event/click_test.dart
> +          'data-test-id': 'the-local-button',
#nit you could probably avoid having to make a separate view and getting by test-id if you use `view.rerender` instead.

2022-04-14 20:43 UTC, sydneyjodon-wk commented on lib/src/user_event/user_event.dart
> +  /// in the DOM-tree has `'pointer-events: none'` set. This check is
Maybe could also add that `click` will usually throw an error if `'pointer-events: none'` is set - so this is changing that

2022-04-14 21:39 UTC, joebingham-wk commented
Good catches, @sydneyjodon-wk! All feedback addressed!

2022-04-14 21:55 UTC, sydneyjodon-wk approved these changes
+10

2022-04-18 16:33 UTC, greglittlefield-wf approved these changes
+1

@Workiva/release-management-p

2022-04-18 16:33 UTC, rmconsole-wf approved these changes
+1 from RM

2022-04-18 16:33 UTC, merged