FED-1155: Migrate to GH deploy pages action
Workiva/react_testing_library pull request #57
Opened 2023-03-13 19:20 UTC by hunterbreathat-wk

## Motivation
Currently we use an action from an individual unverified developer to deploy our GIthub pages, let's migrate to a verified set of actions to reduce risk.

## Changes
- Update Github workflow to verified actions

#### Release Notes
- Update build and deploy docs workflow

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Steps from PR author:
        
    - [ ] Anything falling under manual testing criteria [outlined in CONTRIBUTING.md][contributing-manual-testing]

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Frontend Frameworks Design member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/react_testing_library/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/react_testing_library/blob/master/CONTRIBUTING.md#manual-testing-criteria

2023-03-13 19:21 UTC, aviary2-wf commented
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

2023-03-13 19:21 UTC, hunterbreathat-wk commented
Related docs: 
- https://github.com/marketplace/actions/deploy-github-pages-site
- https://github.com/marketplace/actions/upload-github-pages-artifact

2023-03-14 17:09 UTC, hunterbreathat-wk commented
To have the dev stage pass it would appear that this library needs to be null-safe migrated which is out of scope.

2023-03-20 20:12 UTC, annawatson-wk submitted a review, later dismissed

2023-04-04 16:07 UTC, greglittlefield-wf requested changes

2023-04-04 16:07 UTC, greglittlefield-wf commented on .github/workflows/dart_ci.yml
> -    runs-on: ubuntu-latest
It looks like this removes the run using pubspec.yaml, and the only one left uses pubspec.next.yaml. I'm unfamiliar with what purpose exactly pubspec.next.yaml serves, but if we're publishing using pubspec.yaml, we should be running CI on it.

2023-04-10 19:16 UTC, aaronlademann-wf approved these changes
LGTM

2023-04-13 16:12 UTC, aaronlademann-wf approved these changes
QA +1

@Workiva/release-management-pp

2023-04-13 16:15 UTC, rmconsole-wf approved these changes
+1 from RM

2023-04-13 16:15 UTC, merged